name: singlejob
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: install lint
        run: npm run lint
      - name: test code
        run: npm run test
      - name: run code
        run: npm run build
      - name: deploy  
        run: echo"deploying.........""